In [1]:
import pandas as pd
import numpy as np
import sklearn

In [4]:
raw_df = pd.read_csv('survey.csv', header=1)

In [6]:
raw_df.head(5)

,Unnamed: 0,Timestamp,Name,School,Grade Level(s),Subject Area(s)/ Role,"What’s one thing you feel you NEED to learn this year (due to internal pressures, external pressures, or prior struggles)?",What’s one thing your STUDENTS WANT you to learn this year (to help meet their learning needs)?,"What’s one thing you WANT to learn this year (area to expand/evolve your practice, move to the next level)?",What’s one thing that a TYPICAL TEACHER at your school might benefit from learning this year?,...,Unnamed: 75,10's,20's,30's,40's,Unnamed: 80,50's,60's,70's,80's
0,NaN,NaN,TOTALS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,55,130,11,32,NaN,42,48,65,23
1,1.0,8/15/2018 4:10:01,Mark Lonergan,EMK,9-12,Instructional Coach,Need to learn about new assessment protocols,Not sure yet.,I want to improve my ability to work with stud...,Not sure yet.,...,NaN,1,2,0,0,NaN,0,1,1,1
2,2.0,8/17/2018 10:26:48,Aparna Lakshmi Iyer,O'Bryant,11,Social Studies,How to better support students with chronic at...,How to design more games (we play games to und...,How to better support students on the autism s...,How to improve their communication skills so t...,...,NaN,0,3,3,0,NaN,3,2,1,0
3,3.0,8/21/2018 12:12:48,Tristen Grannum,Boston Latin Academy,8th,English,Project management,Better classroom management,Motivating others,Student voice and agency,...,NaN,0,4,0,0,NaN,1,1,1,0
4,4.0,8/21/2018 12:24:18,Leo Dorest,Timilty Middle School,6-8,Physical Education,NaN,Differentiation,Student demographics. Administrative support,Classroom management,...,NaN,0,5,0,0,NaN,1,0,1,0

In [7]:
raw_df.drop(0, inplace=True)

In [14]:
raw_df.dropna(subset=['Name'], inplace=True)

In [25]:
drop_cols = list(raw_df.notna().sum()[raw_df.notna().sum()==0].index) + [u'Unnamed: 0']

In [26]:
raw_df.drop(drop_cols, axis=1, inplace=True)

In [28]:
raw_df.columns

Index([u'Timestamp', u'Name', u'School', u'Grade Level(s)',
       u'Subject Area(s)/ Role',
       u'What’s one thing you feel you NEED to learn this year (due to internal pressures, external pressures, or prior struggles)?',
       u'What’s one thing your STUDENTS WANT you to learn this year (to help meet their learning needs)?',
       u'What’s one thing you WANT to learn this year (area to expand/evolve your practice, move to the next level)?',
       u'What’s one thing that a TYPICAL TEACHER at your school might benefit from learning this year?',
       u'From the list above (or from elsewhere) what’s a question/challenge/problem of practice that you’d like to address together with colleagues? ',
       u'KEYWORDS', u'11', u'12', u'13', u'14', u'15', u'16', u'21', u'22',
       u'23', u'24', u'25', u'26', u'27', u'28', u'31', u'32', u'33', u'41',
       u'42', u'43', u'44', u'46', u'47', u'50', u'51', u'52', u'53', u'54',
       u'60', u'61', u'62', u'63', u'64', u'70', u'71', u'72', u'74', u'75',
       u'76', u'80', u'81', u'82', u'84', u'85', u'90', u'Tech?', u'10's',
       u'20's', u'30's', u'40's', u'50's', u'60's', u'70's', u'80's'],
      dtype='object')

In [32]:
keep_cols = [u'Timestamp', u'Name', u'School', u'Grade Level(s)',
       u'Subject Area(s)/ Role',
       u'KEYWORDS', u'11', u'12', u'13', u'14', u'15', u'16', u'21', u'22',
       u'23', u'24', u'25', u'26', u'27', u'28', u'31', u'32', u'33', u'41',
       u'42', u'43', u'44', u'46', u'47', u'50', u'51', u'52', u'53', u'54',
       u'60', u'61', u'62', u'63', u'64', u'70', u'71', u'72', u'74', u'75',
       u'76', u'80', u'81', u'82', u'84', u'85', u'90', u'Tech?', u"10's",
       u"20's", u"30's", u"40's", u"50's", u"60's", u"70's", u"80's"]

## Handle Keywords

In [50]:
raw_df['KEYWORDS']=raw_df['KEYWORDS'].apply(set)

In [51]:
raw_df[keep_cols].head(4)

,Timestamp,Name,School,Grade Level(s),Subject Area(s)/ Role,KEYWORDS,11,12,13,14,...,90,Tech?,10's,20's,30's,40's,50's,60's,70's,80's
1,8/15/2018 4:10:01,Mark Lonergan,EMK,9-12,Instructional Coach,"{Differentiation, CDT, SEL, Assessment, Colleg...",NaN,NaN,NaN,1.0,...,NaN,NaN,1,2,0,0,0,1,1,1
2,8/17/2018 10:26:48,Aparna Lakshmi Iyer,O'Bryant,11,Social Studies,"{Student Engagement, Attendance, Student Disco...",NaN,NaN,NaN,NaN,...,NaN,NaN,0,3,3,0,3,2,1,0
3,8/21/2018 12:12:48,Tristen Grannum,Boston Latin Academy,8th,English,"{Student Motivation, Classroom Management, Stu...",NaN,NaN,NaN,NaN,...,NaN,NaN,0,4,0,0,1,1,1,0
4,8/21/2018 12:24:18,Leo Dorest,Timilty Middle School,6-8,Physical Education,"{Differentiation, Classroom Management, Data}",NaN,NaN,NaN,NaN,...,NaN,NaN,0,5,0,0,1,0,1,0

In [53]:
for keyword in set.union(*raw_df.KEYWORDS):
    raw_df[keyword] = raw_df.apply(lambda _: int(keyword in _.KEYWORDS), axis=1)

In [69]:
raw_df['']

1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
24    0
26    0
28    0
30    0
31    0
32    0
33    0
34    0
     ..
47    0
48    0
49    0
50    0
51    0
52    0
53    0
54    0
55    0
56    0
57    0
58    0
59    0
60    1
61    0
62    0
63    0
64    0
65    0
66    0
67    0
68    0
69    0
70    1
71    0
72    0
73    0
74    0
75    0
76    0
Name: , Length: 72, dtype: int64

In [78]:
raw_df.drop('', axis=1, inplace=True)

In [83]:
exclude_cols = [
    'Timestamp',
    'Grade Level(s)',
    'Subject Area(s)/ Role',
     'What\xe2\x80\x99s one thing you feel you NEED to learn this year (due to internal pressures, external pressures, or prior struggles)?',
 'What\xe2\x80\x99s one thing your STUDENTS WANT you to learn this year (to help meet their learning needs)?',
 'What\xe2\x80\x99s one thing you WANT to learn this year (area to expand/evolve your practice, move to the next level)?',
 'What\xe2\x80\x99s one thing that a TYPICAL TEACHER at your school might benefit from learning this year?',
 'From the list above (or from elsewhere) what\xe2\x80\x99s a question/challenge/problem of practice that you\xe2\x80\x99d like to address together with colleagues? ',
 'KEYWORDS',
    "10's",
 "20's",
 "30's",
 "40's",
 "50's",
 "60's",
 "70's",
 "80's"
]

In [84]:
new_df = raw_df.drop(exclude_cols, axis=1)

In [87]:
new_df.fillna(0, inplace=True)

In [88]:
new_df

,Name,School,11,12,13,14,15,16,21,22,...,Inclusion,reading comprehension,CBL,UDL,AP Govt,Differentiation,SpEd,Math methods,Autism,Diagnostic tests
1,Mark Lonergan,EMK,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
2,Aparna Lakshmi Iyer,O'Bryant,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,1,0
3,Tristen Grannum,Boston Latin Academy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
4,Leo Dorest,Timilty Middle School,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,0,0,1,0,0,0,0
5,Monica Gribaudo,Boston Latin School,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
6,Kevin Verrette,Lyon K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
7,Roni Pavick,Lyon K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
8,Frank Swoboda,"English High, The",0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
9,Cristina de Guzman,"English High, The",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,0,0,0
10,Chris Flaherty,Boston Arts Academy,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
11,Marlene Diaz,"English High, The",0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
12,Stephen Bobrow,Boston Arts Academy,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0,0,0,0,0,1,0,0,0,0
13,Keith McCulley,"English High, The",0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
14,Melissa Evans,"English High, The",0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
15,Ingrid Roche,Boston Latin Academy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
16,Quenna Lalonde,"English High, The",0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,1,0,0,0
17,Michael Maguire,Boston Latin Academy,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
18,Weddee Neufville Henry,Charlestown High,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
19,Vicki Cochran,"English High, The",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,1,0,0,0
20,Ryan Gillespie,Excel High,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
21,R Michelle Pierre,West Roxbury Academy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
22,Jen Perry de la Rosa,Boston Latin School,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
24,Rocío,Brighton High,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,1,0,0,0,0
26,Julie Fouhy,Edison K-8,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,1,0,0,0,0,0,0
28,Eva Gerena,Bates Elementary,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,1,0,0,0
30,Jeffrey Banks,Lyon High,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,1,0,0,0,0
31,Jessica Blackler,Boston Latin School,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
32,Heather Kissel,TechBoston Academy,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
33,Ivelisse De Jesus,Community Academy of Science & Health,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
34,John Daley,O'Bryant,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,Angela Lou,Boston Arts Academy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
48,Gina Higgins,Boston Arts Academy,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1,0,0,0,0,1,1,0,0,0
49,Maura Tighe,Boston Arts Academy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
50,Zach Schwartz,Buke High,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
51,Gloria Ojimba,Burke High,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
52,Marques Simpson,CASH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
53,Kwame Adams,Burke High,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
54,Alliberthe Elysee,Higginson Elementary,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
55,Erik M Grau,Higginson Elementary,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
56,Victoria Jordan,Higginson Elementary,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
57,katherine christopher,Higginson Elementary,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
58,William Cotto,Kennedy Academy for Health Careers 9-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,1,0,0,1,0,0,0
59,Keith Magni,Fenway High,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
60,Roudna Joseph,Boston Latin Academy,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61,Lee Franty,Murphy K-8,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1,0,0,0,0,1,0,0,0,0
62,Amy Nguyen,Boston Teachers Union K-8 School,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
63,Joy De Palm,Boston Teachers Union K-8 School,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
64,Felicia Haynes,Mission Hill K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
65,Cleata Brown,Mission Hill K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
66,Geralyn Bywater McLaughlin,Mission Hill K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
67,Leila Parks,Mission Hill K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
68,Daniel Flannery,Mission Hill K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
69,Ashleigh LHeureux,Mission Hill K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
70,Tara Hollins,Frederick Middle,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
71,Jenerra Williams,Mission Hill K-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
72,Capdoagli,Kennedy Academy for Health Careers 11-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,1,0,0,0
73,Kyle Ronan,Horace Mann,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
74,James Anderson,Boston Community Leadership Academy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
75,Mary OBrien,Henderson K-12 Inclusion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
76,Tiana Tassinari,EBHS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,1,0,0,0

In [194]:
training_df = new_df.drop(['School', 'Tech?'], axis=1)

In [198]:
training_df.set_index('Name', inplace=True)

In [208]:
pred_df = pd.DataFrame(np.dot(training_df, training_df.transpose()), index=training_df.index, columns=training_df.index)

In [210]:
pred_df.head(6)

Name,Mark Lonergan,Aparna Lakshmi Iyer,Tristen Grannum,Leo Dorest,Monica Gribaudo,Kevin Verrette,Roni Pavick,Frank Swoboda,Cristina de Guzman,Chris Flaherty,...,Leila Parks,Daniel Flannery,Ashleigh LHeureux,Tara Hollins,Jenerra Williams,Capdoagli,Kyle Ronan,James Anderson,Mary OBrien,Tiana Tassinari
Name,,,,,,,,,,,,,,,,,,,,,
Mark Lonergan,11.0,2.0,1.0,3.0,0.0,1.0,2.0,5.0,0.0,2.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,3.0,0.0
Aparna Lakshmi Iyer,2.0,17.0,5.0,3.0,1.0,3.0,4.0,7.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Tristen Grannum,1.0,5.0,11.0,5.0,0.0,2.0,2.0,6.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Leo Dorest,3.0,3.0,5.0,10.0,1.0,1.0,3.0,7.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
Monica Gribaudo,0.0,1.0,0.0,1.0,8.0,1.0,3.0,3.0,2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kevin Verrette,1.0,3.0,2.0,1.0,1.0,8.0,1.0,3.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [224]:
1.00/10*pred_df.loc['Leo Dorest'].sort_values(ascending=False)[1:4]

Name
Frank Swoboda      0.7
Lee Franty         0.5
Tristen Grannum    0.5
Name: Leo Dorest, dtype: float64

### get recommendations

In [248]:
def match(prediction_df, user_name, threshold=3):
    user_row = prediction_df.loc[user_name]
    weight = user_row[user_name]
    weighted_sorted_user_row = 1.00/weight * user_row.sort_values(ascending=False)
    return weighted_sorted_user_row[1:threshold+1]

In [249]:
match(pred_df, 'Leo Dorest')

Name
Frank Swoboda      0.7
Lee Franty         0.5
Tristen Grannum    0.5
Name: Leo Dorest, dtype: float64

In [250]:
match(pred_df, 'Tristen Grannum')

Name
Julie Fouhy       0.545455
Frank Swoboda     0.545455
Ryan Gillespie    0.545455
Name: Tristen Grannum, dtype: float64

### Get headers

In [101]:
headers_df = pd.read_csv('survey.csv', header=0, nrows=1)

In [114]:
headers_df.dropna(axis=1,inplace=True)

In [140]:
headers_df.drop([u'Unnamed: 1', u'Unnamed: 2', u'Unnamed: 3', u'Unnamed: 4',
       u'Unnamed: 5', u'Unnamed: 6', u'Unnamed: 7', u'Unnamed: 8',
       u'Unnamed: 9', u'Unnamed: 10', u'Unnamed: 12'], axis=1, inplace=True)

In [141]:
col_name_dict = {}

for col in headers_df.columns:
    val = headers_df[col].iloc[0]
    if val in col_name_dict:
        print 'conflict!, {}, {}'.format(val, col)
    else:
        
        col_name_dict[str(val)] = col

In [169]:
new_df_cols = []
for col in list(new_df.columns):
    if col in col_name_dict:
        new_df_cols.append(col_name_dict[col])
    else:
        new_df_cols.append(col)

In [171]:
#need to be careful about headers that have the same names under different subjects